In [1]:
#import zipfile
import numpy as np
import pandas
import os
pandas.options.display.max_colwidth = -1

In [2]:
os.chdir('retrosheet_games/')
years = range(1871,2016+1)
filenames = []
for thisyear in years:
    filenames.append('GL'+str(thisyear)+'.TXT')

#filenames
gamedata = pandas.DataFrame()

list_of_file_contents = []
for thisname in filenames:
#    print('Reading filename: ',thisname)
    df = pandas.read_csv(thisname,header=None)
    list_of_file_contents.append(df)
gamedata = pandas.concat(list_of_file_contents)

os.chdir('../')
#gamedata.tail(30)

# Columns given at http://www.retrosheet.org/gamelogs/glfields.txt
colnames = ['date','gameno','dayofweek']
colnames += ['visitor','visitor_league','visitor_gameno']
colnames += ['home','home_league','home_gameno']
colnames += ['visitor_score','home_score']
colnames += ['nOuts','day_night','completed','forfeit','protest','parkID','attendance','length']
colnames += ['visitor_linescore','home_linescore']
colnames += ['visitor_ab','visitor_h','visitor_2b','visitor_3b','visitor_hr']
colnames += ['visitor_rbi','visitor_sac','visitor_sacfly','visitor_hbp']
colnames += ['visitor_bb','visitor_ibb','visitor_k','visitor_sb','visitor_cs']
colnames += ['visitor_gidp','visitor_ci','visitor_lob','visitor_nPitchers']
colnames += ['visitor_er_ind','visitor_er_team','visitor_wp','visitor_balk']
colnames += ['visitor_putout','visitor_assist','visitor_e','visitor_pb']
colnames += ['visitor_dp','visitor_tp','home_ab','home_h','home_2b','home_3b']
colnames += ['home_hr','home_rbi','home_sac','home_sacfly','home_hbp','home_bb']
colnames += ['home_ibb','home_k','home_sb','home_cs','home_gidp','home_ci']
colnames += ['home_lob','home_nPitchers','home_er_ind','home_er_team','home_wp']
colnames += ['home_balk','home_putout','home_assist','home_e','home_pb']
colnames += ['home_dp','home_tp']
colnames += ['ump_home_id','ump_home_name','ump_1b_id']
colnames += ['ump_1b_name','ump_2b_id','ump_2b_name','ump_3b_id','ump_3b_name']
colnames += ['ump_lf_id','ump_lf_name','ump_rf_id','ump_rf_name']
colnames += ['visitor_manager_id','visitor_manager_name','home_manager_id','home_manager_name']
colnames += ['winning_pitcher_id','winning_pitcher_name','losing_pitcher_id']
colnames += ['losing_pitcher_name','saving_pitcher_id','saving_pitcher_name']
colnames += ['gw_rbi_batter_id','gw_rbi_batter_name','visitor_starting_pitcher_id']
colnames += ['visitor_starting_pitcher_name','home_starting_pitcher_id']
colnames += ['home_starting_pitcher_name']
colnames += ['visitor_batter1_id','visitor_batter1_name','visitor_batter1_pos']
colnames += ['visitor_batter2_id','visitor_batter2_name','visitor_batter2_pos']
colnames += ['visitor_batter3_id','visitor_batter3_name','visitor_batter3_pos']
colnames += ['visitor_batter4_id','visitor_batter4_name','visitor_batter4_pos']
colnames += ['visitor_batter5_id','visitor_batter5_name','visitor_batter5_pos']
colnames += ['visitor_batter6_id','visitor_batter6_name','visitor_batter6_pos']
colnames += ['visitor_batter7_id','visitor_batter7_name','visitor_batter7_pos']
colnames += ['visitor_batter8_id','visitor_batter8_name','visitor_batter8_pos']
colnames += ['visitor_batter9_id','visitor_batter9_name','visitor_batter9_pos']
colnames += ['home_batter1_id','home_batter1_name','home_batter1_pos']
colnames += ['home_batter2_id','home_batter2_name','home_batter2_pos']
colnames += ['home_batter3_id','home_batter3_name','home_batter3_pos']
colnames += ['home_batter4_id','home_batter4_name','home_batter4_pos']
colnames += ['home_batter5_id','home_batter5_name','home_batter5_pos']
colnames += ['home_batter6_id','home_batter6_name','home_batter6_pos']
colnames += ['home_batter7_id','home_batter7_name','home_batter7_pos']
colnames += ['home_batter8_id','home_batter8_name','home_batter8_pos']
colnames += ['home_batter9_id','home_batter9_name','home_batter9_pos']
colnames += ['misc','acquisition']
gamedata.columns = colnames
gamedata = gamedata.reset_index()
gamedata = gamedata.drop('index',axis=1)
gamedata.index.name = 'gameID'
print('{:,.0f} games parsed'.format(len(gamedata)))
gamedata.head(1).transpose()

213,307 games parsed

gameID                             0
date                 18710504
gameno               0
dayofweek            Thu
visitor              CL1
visitor_league       na
visitor_gameno       1
home                 FW1
home_league          na
home_gameno          1
visitor_score        0
home_score           2
nOuts                54
day_night            D
completed            NaN
forfeit              NaN
protest              NaN
parkID               FOR01
attendance           200
length               120
visitor_linescore    000000000
home_linescore       010010000
visitor_ab           30
visitor_h            4
visitor_2b           1
visitor_3b           0
visitor_hr           0
visitor_rbi          0
visitor_sac          0
visitor_sacfly       0
visitor_hbp          0
...                 ..
visitor_batter9_pos  6
home_batter1_id      selmf101
home_batter1_name    Frank Sellman
home_batter1_pos     5
home_batter2_id      mathb101
home_batter2_name    Bobby Mathews
home_batter2_pos     1
home_batter3_id      foraj101
home_batter3_name    Jim Foran
home_batter3_pos     3
home_batter4_id      goldw101
home_batter4_name    Wally Goldsmith
home_batter4_pos     6
home_batter5_id      lennb101
home_batter5_name    Bill Lennon
home_batter5_pos     2
home_batter6_id      caret101
home_batter6_name    Tom Carey
home_batter6_pos     4
home_batter7_id      mince101
home_batter7_name    Ed Mincher
home_batter7_pos     7
home_batter8_id      mcdej101
home_batter8_name    James McDermott
home_batter8_pos     8
home_batter9_id      kellb105
home_batter9_name    Bill Kelly
home_batter9_pos     9
misc                 NaN
acquisition          Y

[161 rows x 1 columns]

In [3]:
gamedata.to_csv('gamedata.csv')
print('done')

done